[package]
name = "option-pricer"
version = "0.1.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.7.8"
structopt = "0.3"
libm = "0.2.1"
statrs = "0.6.0"